import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useSession, signIn, signOut, getSession} from "next-auth/react"
import { useRouter } from 'next/router'
import HeadersHome from '../components/HeadersHome'
import Video from '../components/Video'
import Masonry from '../components/Masonry'

export default function Home() {

const router = useRouter()

    return (
      <div className="bg-gray-50 w-full h-full">
        <Head>
          <title>PUSKESMAS LASEM</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
           <HeadersHome />
         <Video />
        <main className={styles.main}>
          <Masonry />
          <div className={styles.grid}>
            <div className={styles.card}>
              <h2>Profesionalitas</h2>
              <p>Bekerja Dengan Smart & Professional</p>
            </div>
            <div className={styles.card}>
              <h2>Bekerja Dengan Hati</h2>
              <p>Selalu Siap Membantu dan Melayani</p>
            </div>
            <div className={styles.card}>
              <h2>Bekerja Adalah Ibadah</h2>
              <p>Menyapa dengan senyum dan ramah tamah</p>
            </div>
  
          
            
  
            
          </div>
        </main>
  
        <footer className={styles.footer}>
          <div
           
          >
            Powered by{' '}
            <span className={styles.logo}>
              Blambangan Digital
            </span>
          </div>
        </footer>
      </div>
    )
  } 

  export async function getServerSideProps(context) {
    const session = await getSession(context)
    if (session) {
      return {
        redirect: {
          permanent: false,
          destination: "/",
        },
      };
    }
     return {
       props: {
         session
       }
     };
   }